version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '35432:5432'
    volumes:
      - test-db:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - postgres
    command:
      - /bin/bash
      - -c
      - |
        yarn build
        yarn start:prod
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_DATABASE: postgres
    ports:
      - '4000:4000'
volumes:
  test-db:

